import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/src/components/Navbar";
import SubMenu from "@/src/components/subMenu";
import Footer from "@/src/components/footer";
import Sidebar from "@/src/components/sidebar";
// import Loading from "@/src/providers/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StarBucks Menu",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
    apple: ["/favicon.ico"],
    shortcut: ["favicon.ico"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#0b7555" />
      <body className={inter.className}>
        {/* <Loading> */}
        <Navbar />
        {children}
        <Footer />
        {/* </Loading> */}
      </body>
    </html>
  );
}
